### ISSUE TITLE
Pre-training models

### ISSUE THREAD

**Issue by Zhouhrzz** [NaJaeMin92/CoVi#1]
What datasets are used to train the pre-training models of DANN and MSTN? Can you provide a pre-trained model or code? Thank you very much!

**Comment by Arsiuuu** [comment]
Hi~ I've met the same question. Have you found the pretrained model?

**Comment by Zhouhrzz** [comment]
no....

**Comment by Arsiuuu** [comment]
Have you reproduce the result without pretrained model? Now my best acc is 74% when the 10epoch (OFFICE31 A->W)

**Comment by PanHunger** [comment]
> Have you reproduce the result without pretrained model? Now my best acc is 74% when the 10epoch (OFFICE31 A->W)

me toooooo

**Comment by Zhouhrzz** [comment]
Do you know what is the network version？

Traceback (most recent call last):
File "main.py", line 9, in
import utils
File "/home/zhouwenshuo/workspace/domain_shift/nature/CoVi-master/utils.py", line 7, in
from network import models
ImportError: cannot import name 'models' from 'network' (/home/zhouwenshuo/anaconda3/envs/p38t/lib/python3.8/site-packages/network.py)`
