### ISSUE TITLE
What is the `network` version？

### ISSUE THREAD

**Issue by zws-2019** [NaJaeMin92/CoVi#2]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    import utils
  File "/home/zhouwenshuo/workspace/domain_shift/nature/CoVi-master/utils.py", line 7, in <module>
    from network import models
ImportError: cannot import name 'models' from 'network' (/home/zhouwenshuo/anaconda3/envs/p38t/lib/python3.8/site-packages/network.py)`

**Comment by yulong-ge** [comment]
This should be the wrong module. The source code is written to import models from network, but in fact, just change it to import models directly.
